image: gitpod/workspace-python-3.11

tasks:
  - name: setup
    command: printf '%s\n' "export AIRFLOW_HOME=/workspace/airflow_demo" >> "$HOME/.bashrc"
  - name: airflow
    init: pip install "apache-airflow==2.7.3" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.7.3/constraints-3.11.txt"
  - name: databricks
    init: pip install "apache-airflow-providers-databricks==5.0.1"
