image: gitpod/workspace-python-3.11

tasks:
  - name: setup
    command: printf '%s\n' "export AIRFLOW_HOME=/workspace/airflow_demo" >> "$HOME/.bashrc"
  - name: airflow
    init: pip install "apache-airflow==2.9.1" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.1/constraints-3.11.txt"
  
